apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp2
spec:
  selector:
    matchLabels:
      app: web2
  replicas: 2
  template:
    metadata:
      labels:
        app: web2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web2
  labels:
    name: web2
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: web2